rootProject.name = "CleverFerretV2"

include(":app")
include(":core:common")
include(":core:ui")
include(":core:data")
include(":core:network")
include(":core:database")
include(":core:media")
include(":core:auth")
include(":feature:library")
include(":feature:reader")
include(":feature:audio")
include(":feature:radio")
include(":feature:podcast")
include(":feature:webfiction")
include(":feature:metadata")
include(":feature:sync")
include(":feature:opds")
include(":feature:plex")
include(":feature:settings")
include(":feature:search")
include(":feature:collections")
include(":feature:stats")
include(":feature:widgets")
