import org.gradle.api.JavaVersion

/**
 * Universal Media Library - Root Build Configuration
 *
 * Top-level build file for project-wide plugin versions and configuration.
 * Individual module configurations are in their respective build.gradle.kts files.
 *
 * Canonical toolchain versions:
 * - AGP/Kotlin/KSP/Hilt plugin versions: gradle/libs.versions.toml ([versions] + [plugins])
 * - Gradle runtime version: gradle/wrapper/gradle-wrapper.properties (distributionUrl)
 *
 * Upgrade procedure:
 * 1) Update plugin/tool versions in gradle/libs.versions.toml.
 * 2) Update Gradle wrapper via ./gradlew wrapper --gradle-version <version>.
 * 3) Run ./gradlew --version and ./gradlew help to validate the toolchain.
 * See docs/BUILD_TOOLCHAIN_VERSIONS.md for full details.
 */

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.hilt) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.detekt)
}

detekt {
    buildUponDefaultConfig = true
    allRules = false
    config.setFrom(files("$rootDir/config/detekt/detekt.yml"))
    baseline = file("$rootDir/CleverFerret/detekt-baseline.xml")
}

val supportedGradleRuntimeJdks = 17..21
val currentRuntimeJdk = JavaVersion.current().majorVersion.toIntOrNull()

check(currentRuntimeJdk != null && currentRuntimeJdk in supportedGradleRuntimeJdks) {
    """
Unsupported Java runtime for this AGP/Kotlin toolchain: ${JavaVersion.current()}.
Use JDK 17 through JDK 21 to run Gradle (current: ${System.getProperty("java.version")}).
See docs/BUILD_TOOLCHAIN_VERSIONS.md for local/CI setup instructions.
""".trimIndent()
}

allprojects {
    dependencyLocking {
        lockAllConfigurations()
    }
    configurations.all {
        resolutionStrategy {
            force("org.jetbrains.kotlin:kotlin-stdlib:2.1.0")
            force("org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.0")
            force("org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.1.0")
            eachDependency {
                if (requested.group == "org.jetbrains.kotlin" && requested.name == "kotlin-stdlib-common") {
                    useTarget("org.jetbrains.kotlin:kotlin-stdlib:2.1.0")
                }
            }
        }
    }
}

val hookContent = """
#!/usr/bin/env bash
set -euo pipefail

# Pre-commit Git Hook generated by Gradle (./gradlew installGitHooks)

echo "==> Running pre-commit static analysis checks..."

STAGED_FILES=${'$'}(git diff --cached --name-only --diff-filter=ACM || true)

if [ -z "${'$'}STAGED_FILES" ]; then
    echo "No staged files detected. Skipping pre-commit checks."
    exit 0
fi

HAS_KOTLIN=0
HAS_DOCS=0
HAS_SRC=0

while IFS= read -r file; do
    if [[ "${'$'}file" =~ \.(kt|kts)$ ]]; then
        HAS_KOTLIN=1
    fi
    if [[ "${'$'}file" =~ \.(md|markdown)$ ]] || [[ "${'$'}file" =~ ^docs/ ]]; then
        HAS_DOCS=1
    fi
    if [[ "${'$'}file" =~ ^CleverFerret/src/ ]] || [[ "${'$'}file" =~ ^CleverFerretV2/ ]]; then
        HAS_SRC=1
    fi
done <<< "${'$'}STAGED_FILES"

has_android_sdk() {
    if [ -n "${'$'}{ANDROID_HOME:-}" ] && [ -d "${'$'}ANDROID_HOME" ]; then
        return 0
    fi
    if [ -n "${'$'}{ANDROID_SDK_ROOT:-}" ] && [ -d "${'$'}ANDROID_SDK_ROOT" ]; then
        return 0
    fi
    if [ -f "local.properties" ]; then
        SDK_DIR=${'$'}(grep -E '^sdk\.dir=' local.properties | cut -d'=' -f2 | tr -d ' \r' || true)
        if [ -n "${'$'}SDK_DIR" ] && [ -d "${'$'}SDK_DIR" ]; then
            return 0
        fi
    fi
    if [ -d "/usr/local/lib/android/sdk" ] || [ -d "${'$'}HOME/Android/Sdk" ]; then
        return 0
    fi
    return 1
}

EXIT_CODE=0

if [ "${'$'}HAS_KOTLIN" -eq 1 ]; then
    if has_android_sdk; then
        echo "--> Running Detekt static analysis on Kotlin sources..."
        if ! ./gradlew detekt -Dorg.gradle.daemon=true --quiet; then
            echo "❌ Detekt analysis failed! Please fix rule violations before committing."
            EXIT_CODE=1
        fi
    else
        echo "⚠️ Android SDK not found. Skipping Detekt compilation check; running non-SDK checks."
    fi
fi

if [ "${'$'}HAS_SRC" -eq 1 ] || [ "${'$'}HAS_KOTLIN" -eq 1 ]; then
    echo "--> Checking for raw console usage in production paths..."
    if [ -f "./scripts/check-no-raw-console.sh" ]; then
        if ! bash ./scripts/check-no-raw-console.sh; then
            echo "❌ Raw console check failed!"
            EXIT_CODE=1
        fi
    fi
fi

if [ "${'$'}HAS_DOCS" -eq 1 ]; then
    echo "--> Validating documentation local links..."
    if [ -f "./scripts/ci/check_doc_links.py" ]; then
        if ! python3 ./scripts/ci/check_doc_links.py; then
            echo "❌ Documentation links check failed!"
            EXIT_CODE=1
        fi
    fi
fi

if [ "${'$'}EXIT_CODE" -ne 0 ]; then
    echo "❌ Pre-commit checks failed. Commit aborted."
    exit 1
fi

echo "✅ All pre-commit checks passed successfully!"
exit 0
""".trimIndent()

tasks.register("installGitHooks") {
    group = "verification"
    description = "Installs Git pre-commit hook into .git/hooks directory."

    val gitHooksDir = rootProject.file(".git/hooks")
    val preCommitFile = File(gitHooksDir, "pre-commit")

    outputs.file(preCommitFile)

    doLast {
        if (rootProject.file(".git").exists()) {
            if (!gitHooksDir.exists()) {
                gitHooksDir.mkdirs()
            }
            preCommitFile.writeText(hookContent + "\n")
            preCommitFile.setExecutable(true, false)
            logger.lifecycle("Installed Git pre-commit hook at ${preCommitFile.absolutePath}")
        } else {
            logger.warn("Skipping installGitHooks: .git directory not found.")
        }
    }
}

tasks.register<Exec>("checkNoRawConsole") {
    group = "verification"
    description = "Checks production source code for raw console usage."
    commandLine("bash", rootProject.file("scripts/check-no-raw-console.sh"))
}

tasks.register<Exec>("checkDocLinks") {
    group = "verification"
    description = "Validates local markdown documentation links."
    commandLine("python3", rootProject.file("scripts/ci/check_doc_links.py"))
}

// Auto-install Git hooks during build initialization / evaluation if .git exists
gradle.projectsEvaluated {
    val gitHooksDir = rootProject.file(".git/hooks")
    if (rootProject.file(".git").exists()) {
        if (!gitHooksDir.exists()) {
            gitHooksDir.mkdirs()
        }
        val preCommitFile = File(gitHooksDir, "pre-commit")
        if (!preCommitFile.exists() || preCommitFile.readText().trim() != hookContent.trim()) {
            preCommitFile.writeText(hookContent + "\n")
            preCommitFile.setExecutable(true, false)
        }
    }
}

