
import { MediaItem, MediaType } from './types';

export const MOCK_MEDIA_ITEMS: MediaItem[] = [
  {
    id: 'book-1',
    type: MediaType.Book,
    title: 'Dune',
    authors: ['Frank Herbert'],
    series: 'Dune Saga',
    seriesIndex: 1,
    summary: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the “spice” melange, a drug capable of extending life and enhancing consciousness.',
    rating: 5,
    releaseDate: '1965-08-01',
    genres: ['Science Fiction', 'Adventure'],
    publisher: 'Chilton Books',
    isbn: '978-0441013593',
    coverArt: 'https://picsum.photos/seed/dune/400/600',
    status: 'Finished',
    dateAdded: '2023-01-15',
  },
  {
    id: 'movie-1',
    type: MediaType.Movie,
    title: 'Blade Runner 2049',
    directors: ['Denis Villeneuve'],
    artists: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas'],
    summary: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    rating: 5,
    releaseDate: '2017-10-06',
    genres: ['Science Fiction', 'Neo-noir', 'Thriller'],
    coverArt: 'https://picsum.photos/seed/bladerunner/400/600',
    status: 'Watched',
    dateAdded: '2023-03-20',
  },
  {
    id: 'music-1',
    type: MediaType.Music,
    title: 'Discovery',
    artists: ['Daft Punk'],
    summary: 'The second studio album by the French electronic music duo Daft Punk, released on 26 February 2001 by Virgin Records.',
    rating: 5,
    releaseDate: '2001-02-26',
    genres: ['Electronic', 'House', 'Disco'],
    coverArt: 'https://picsum.photos/seed/discovery/400/400',
    status: 'Finished',
    dateAdded: '2022-11-10',
  },
  {
    id: 'book-2',
    type: MediaType.Book,
    title: 'Neuromancer',
    authors: ['William Gibson'],
    summary: 'The story of a washed-up computer hacker hired by a mysterious employer to pull off the ultimate hack.',
    rating: 4,
    releaseDate: '1984-07-01',
    genres: ['Science Fiction', 'Cyberpunk'],
    publisher: 'Ace Books',
    isbn: '978-0441569595',
    coverArt: 'https://picsum.photos/seed/neuromancer/400/600',
    status: 'Reading',
    dateAdded: '2023-05-01',
  },
   {
    id: 'movie-2',
    type: MediaType.Movie,
    title: 'Inception',
    directors: ['Christopher Nolan'],
    artists: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    summary: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    rating: 5,
    releaseDate: '2010-07-16',
    genres: ['Science Fiction', 'Action', 'Heist'],
    coverArt: 'https://picsum.photos/seed/inception/400/600',
    status: 'Unwatched',
    dateAdded: '2023-08-11',
  },
   {
    id: 'comic-1',
    type: MediaType.Comic,
    title: 'Watchmen',
    authors: ['Alan Moore'],
    artists: ['Dave Gibbons'],
    summary: 'In an alternate history where superheroes are treated as outlaws, a murder investigation uncovers a sinister plot that could change the course of history.',
    rating: 5,
    releaseDate: '1986-09-01',
    genres: ['Superhero', 'Mystery', 'Dystopian'],
    publisher: 'DC Comics',
    coverArt: 'https://picsum.photos/seed/watchmen/400/600',
    status: 'Finished',
    dateAdded: '2022-09-05',
  },
  {
    id: 'podcast-1',
    type: MediaType.Podcast,
    title: 'The Daily',
    artists: ['The New York Times'],
    summary: 'This is what the news should sound like. The biggest stories of our time, told by the best journalists in the world. Hosted by Michael Barbaro and Sabrina Tavernise. Twenty minutes a day, five days a week, ready by 6 a.m.',
    genres: ['News', 'Current Events'],
    coverArt: 'https://picsum.photos/seed/thedaily/400/400',
    status: 'Reading', // Using 'Reading' for listening
    dateAdded: '2023-10-01',
  },
];
